### ISSUE TITLE
Use of UniquePersonList

### ISSUE THREAD

**Issue by Mohammed-Faizzzz** [AY2324S1-CS2103T-T09-3/tp#132]
I am unsure what UniquePersonList does. We need to refactor it to include Patients if needed. If UniquePersonList is sufficient, delete UniqueDoctorList.

**Comment by Mohammed-Faizzzz** [comment]
UniquePersonList is sufficient, delete UniqueDoctorList.

**Comment by chonguschonguschongus** [comment]
UniquePersonList is a generic class that can be used with any child class of Person. Useful for future developers that want to implement more Person types and have it work with UniquePersonList
