### ISSUE TITLE
[PE-D][Tester A] Phone numbers can be less than 8 digits

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T09-3/tp#168]
While it is stated than phone numbers must be exactly 8 digits. Users can add 123456 for example.

![image.png](https://raw.githubusercontent.com/RoeReRe/ped/main/files/b72da636-d657-4208-ac51-9f3635e5602f.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: RoeReRe/ped#2

**Comment by kohkaijie** [comment]
This seems to be more of a UG bug. The UG specifies that phone numbers should be exactly 8 digits long, but our isValidPhoneNumber method checks that it is at least 3 digits long, and the error message thrown also seems to match that. Will need to update UG accordingly.

**Comment by cmHuang777** [comment]
As discussed, we will change the UG to update the restrictions for phone numbers to be 3 digits instead.
