### ISSUE TITLE
[PE-D][Tester D] edit feature bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T09-3/tp#170]
The edit command passes even when no real edits are being made (same information is used)
![image.png](https://raw.githubusercontent.com/nicolengk/ped/main/files/82ca3150-e2aa-4c4f-8381-59716a91c154.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: nicolengk/ped#1

**Comment by cmHuang777** [comment]
We should just specify in the UG that editing with the same information is still allowed.
