### ISSUE TITLE
[PE-D][Tester D] Stacking appointment bug

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T09-3/tp#176]
Command passes even if patient already has 2 existing back to back appointments, which is not very realistic and does not fit well with the product
![image.png](https://raw.githubusercontent.com/nicolengk/ped/main/files/bd323ea2-13d9-4bc1-a50f-595badb4b98d.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: nicolengk/ped#2

**Comment by cmHuang777** [comment]
Personally, I feel this is a documentation issue where we should specify this is not a bug. I think how long the appointment is, is up to the clinic and we should provide them the flexibility to input that themselves. However, may be we can have a 5 minutes buffer instead, but this requires more discussion.

**Comment by cmHuang777** [comment]
As discussed, we will just update UG to mention users are allowed to add appointments as long as they are not at the exact same time.
