### ISSUE TITLE
[PE-D][Tester A] Long inputs are not visible on the GUI

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-T09-3/tp#205]
![image.png](https://raw.githubusercontent.com/RoeReRe/ped/main/files/18c46c05-3e94-47fb-a3d1-66012ce22af7.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: RoeReRe/ped#11

**Comment by chonguschonguschongus** [comment]
enable text wrapping

**Comment by cmHuang777** [comment]
As discussed, we will allow text-wrapping since there are no other ways users can currently view long inputs
