### ISSUE TITLE
Wrong Error Message

### ISSUE THREAD

**Issue by cmHuang777** [AY2324S1-CS2103T-T09-3/tp#224]
![image](https://github.com/AY2324S1-CS2103T-T09-3/tp/assets/119959360/58946550-741c-4207-9271-009606cfa1b7)

Error message for invalid find says "a list with index numbers", but there should not be any index

**Comment by kohkaijie** [comment]
technically its correct right cos the list will be like 1. Alex Yeoh 2. John Doe which is a list with index numbers
